// ============================================
// Mock Data (Temporary until API integration)
// ============================================

import type { Product, AdminProduct, Order, CustomOrder, DashboardStats } from '@/types';

// Import images
import vanillaCake from '@/assets/vanilla-cake.jpg';
import blackforestCake from '@/assets/blackforest-cake.jpg';
import chocolateCake from '@/assets/chocolate-cake.jpg';
import whiteforestCake from '@/assets/whiteforest-cake.jpg';
import birthdayDecor from '@/assets/birthday-decor.jpg';
import anniversaryDecor from '@/assets/anniversary-decor.jpg';
import weddingDecor from '@/assets/wedding-decor.jpg';

// Products Mock Data
export const MOCK_PRODUCTS: Product[] = [
  // Cakes
  {
    id: 'vanilla-cake',
    name: 'Vanilla Dream Cake',
    category: 'cakes',
    subcategory: 'vanilla',
    occasion: ['birthday', 'anniversary'],
    price: 450,
    pricePerLb: true,
    image: vanillaCake,
    galleryImages: [chocolateCake, whiteforestCake, blackforestCake],
    description: 'Light and fluffy vanilla sponge layered with fresh cream and vanilla buttercream. A timeless classic for all celebrations.',
    tags: ['fresh cream', 'custom message', 'bestseller'],
    available: true,
    popular: true,
    sizes: [1, 2, 3, 5],
  },
  {
    id: 'blackforest-cake',
    name: 'Black Forest Delight',
    category: 'cakes',
    subcategory: 'blackforest',
    occasion: ['birthday', 'anniversary'],
    price: 550,
    pricePerLb: true,
    image: blackforestCake,
    galleryImages: [vanillaCake, chocolateCake, whiteforestCake],
    description: 'Rich chocolate layers with cherry filling, whipped cream, and chocolate shavings. A German classic loved by all.',
    tags: ['chocolate', 'cherry', 'fresh cream', 'custom message'],
    available: true,
    popular: true,
    sizes: [1, 2, 3, 5],
  },
  {
    id: 'chocolate-cake',
    name: 'Belgian Chocolate Cake',
    category: 'cakes',
    subcategory: 'chocolate',
    occasion: ['birthday', 'anniversary', 'wedding'],
    price: 600,
    pricePerLb: true,
    image: chocolateCake,
    galleryImages: [blackforestCake, vanillaCake, whiteforestCake],
    description: 'Decadent Belgian chocolate cake with dark chocolate ganache. For true chocolate lovers.',
    tags: ['dark chocolate', 'ganache', 'premium', 'custom message'],
    available: true,
    popular: true,
    sizes: [1, 2, 3, 5],
  },
  {
    id: 'whiteforest-cake',
    name: 'White Forest Elegance',
    category: 'cakes',
    subcategory: 'whiteforest',
    occasion: ['wedding', 'anniversary'],
    price: 580,
    pricePerLb: true,
    image: whiteforestCake,
    galleryImages: [vanillaCake, chocolateCake, blackforestCake],
    description: 'Delicate white chocolate sponge with cream cheese frosting and white chocolate curls. Pure elegance.',
    tags: ['white chocolate', 'cream cheese', 'elegant', 'custom message'],
    available: true,
    popular: false,
    sizes: [1, 2, 3, 5],
  },
  {
    id: 'eggless-vanilla',
    name: 'Eggless Vanilla Cake',
    category: 'cakes',
    subcategory: 'vanilla',
    occasion: ['birthday', 'anniversary'],
    price: 480,
    pricePerLb: true,
    image: vanillaCake,
    galleryImages: [chocolateCake, whiteforestCake],
    description: 'Our signature eggless vanilla cake, just as soft and delicious. Perfect for vegetarian celebrations.',
    tags: ['eggless', 'vegetarian', 'fresh cream', 'custom message'],
    available: true,
    popular: true,
    sizes: [1, 2, 3, 5],
  },
  {
    id: 'truffle-chocolate',
    name: 'Chocolate Truffle Cake',
    category: 'cakes',
    subcategory: 'chocolate',
    occasion: ['birthday', 'anniversary'],
    price: 650,
    pricePerLb: true,
    image: chocolateCake,
    galleryImages: [blackforestCake, whiteforestCake, vanillaCake],
    description: 'Intensely chocolatey truffle cake with a smooth, melt-in-mouth texture. A chocolate lover\'s dream.',
    tags: ['truffle', 'premium', 'rich', 'custom message'],
    available: true,
    popular: true,
    sizes: [1, 2, 3, 5],
  },
  // Decoration Items
  {
    id: 'birthday-balloon-set',
    name: 'Birthday Balloon Set',
    category: 'decoration',
    occasion: ['birthday'],
    price: 299,
    image: birthdayDecor,
    galleryImages: [anniversaryDecor, weddingDecor],
    description: 'Colorful balloon set with \'Happy Birthday\' foil balloon, 20 latex balloons, and ribbon.',
    tags: ['balloons', 'colorful', 'party'],
    available: true,
    popular: true,
  },
  {
    id: 'birthday-banner-candles',
    name: 'Birthday Banner & Candles Kit',
    category: 'decoration',
    occasion: ['birthday'],
    price: 199,
    image: birthdayDecor,
    galleryImages: [anniversaryDecor],
    description: 'Golden \'Happy Birthday\' banner with matching number candles and sparkler candles.',
    tags: ['banner', 'candles', 'golden'],
    available: true,
    popular: false,
  },
  {
    id: 'anniversary-banner',
    name: 'Anniversary Banner & Candles',
    category: 'decoration',
    occasion: ['anniversary'],
    price: 349,
    image: anniversaryDecor,
    galleryImages: [weddingDecor, birthdayDecor],
    description: 'Elegant rose gold \'Happy Anniversary\' banner with heart-shaped balloons and romantic candles.',
    tags: ['rose gold', 'romantic', 'hearts'],
    available: true,
    popular: true,
  },
  {
    id: 'anniversary-table-decor',
    name: 'Anniversary Table Decoration',
    category: 'decoration',
    occasion: ['anniversary'],
    price: 499,
    image: anniversaryDecor,
    galleryImages: [weddingDecor],
    description: 'Complete table decoration set with rose petals, tea lights, and photo frame centerpiece.',
    tags: ['romantic', 'roses', 'premium'],
    available: true,
    popular: false,
  },
  {
    id: 'wedding-table-decor',
    name: 'Wedding Table Decor Pack',
    category: 'decoration',
    occasion: ['wedding'],
    price: 899,
    image: weddingDecor,
    galleryImages: [anniversaryDecor, birthdayDecor],
    description: 'Elegant wedding table decoration with white flowers, crystal votive holders, and satin runners.',
    tags: ['elegant', 'white', 'premium', 'crystals'],
    available: true,
    popular: true,
  },
  {
    id: 'wedding-backdrop',
    name: 'Wedding Photo Backdrop',
    category: 'decoration',
    occasion: ['wedding'],
    price: 1299,
    image: weddingDecor,
    galleryImages: [anniversaryDecor],
    description: 'Stunning floral backdrop for wedding photos with fairy lights and draped fabric.',
    tags: ['backdrop', 'flowers', 'fairy lights', 'premium'],
    available: true,
    popular: false,
  },
];

// Admin Products Mock Data (with additional fields)
export const MOCK_ADMIN_PRODUCTS: AdminProduct[] = MOCK_PRODUCTS.map((product, index) => ({
  ...product,
  sku: `${product.category.toUpperCase().slice(0, 3)}-${product.id.slice(0, 3).toUpperCase()}-${String(index + 1).padStart(3, '0')}`,
  stock: Math.floor(Math.random() * 100) + 10,
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date('2024-01-20'),
}));

// Orders Mock Data
export const MOCK_ORDERS: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD-2024-001',
    customerName: 'Ram Sharma',
    phone: '+977 9841234567',
    email: 'ram@example.com',
    address: 'Kathmandu, Nepal',
    deliveryType: 'delivery',
    deliveryDate: new Date('2024-01-25'),
    deliveryTime: '2:00 PM',
    items: [
      {
        id: '1',
        productId: 'vanilla-cake',
        productName: 'Vanilla Dream Cake',
        productImage: vanillaCake,
        quantity: 1,
        size: 2,
        price: 900,
        notes: 'Write "Happy Birthday Sita"',
      },
      {
        id: '2',
        productId: 'birthday-balloon-set',
        productName: 'Birthday Balloon Set',
        productImage: birthdayDecor,
        quantity: 1,
        price: 299,
      },
    ],
    subtotal: 1199,
    deliveryFee: 100,
    total: 1299,
    status: 'pending',
    notes: 'Please deliver before 2 PM',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    orderNumber: 'ORD-2024-002',
    customerName: 'Sita Devi',
    phone: '+977 9851234567',
    deliveryType: 'pickup',
    deliveryDate: new Date('2024-01-26'),
    deliveryTime: '10:00 AM',
    items: [
      {
        id: '3',
        productId: 'chocolate-cake',
        productName: 'Belgian Chocolate Cake',
        productImage: chocolateCake,
        quantity: 1,
        size: 3,
        price: 1800,
      },
    ],
    subtotal: 1800,
    deliveryFee: 0,
    total: 1800,
    status: 'confirmed',
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '3',
    orderNumber: 'ORD-2024-003',
    customerName: 'Krishna Bahadur',
    phone: '+977 9861234567',
    email: 'krishna@example.com',
    address: 'Lalitpur, Nepal',
    deliveryType: 'delivery',
    deliveryDate: new Date('2024-01-27'),
    items: [
      {
        id: '4',
        productId: 'vanilla-cake',
        productName: 'Vanilla Dream Cake',
        productImage: vanillaCake,
        quantity: 2,
        size: 1,
        price: 900,
      },
    ],
    subtotal: 900,
    deliveryFee: 150,
    total: 1050,
    status: 'delivered',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-27'),
  },
];

// Custom Orders Mock Data
export const MOCK_CUSTOM_ORDERS: CustomOrder[] = [
  {
    id: '1',
    customerName: 'Gita Kumari',
    phone: '+977 9871234567',
    email: 'gita@example.com',
    cakeDetails: 'I want a 3-tier wedding cake with white fondant and fresh flowers decoration. The cake should be vanilla with strawberry filling. Need it for 200 guests.',
    preferredDate: new Date('2024-02-14'),
    status: 'new',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '2',
    customerName: 'Hari Prasad',
    phone: '+977 9881234567',
    cakeDetails: 'Custom photo cake with my daughters photo for her 5th birthday. 2 lb chocolate cake.',
    preferredDate: new Date('2024-01-30'),
    referenceImage: chocolateCake,
    status: 'contacted',
    adminNotes: 'Called customer, confirmed design requirements',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '3',
    customerName: 'Maya Tamang',
    phone: '+977 9891234567',
    email: 'maya@example.com',
    cakeDetails: 'Need a eggless black forest cake for office party. Around 5 lbs with company logo on top.',
    preferredDate: new Date('2024-02-01'),
    status: 'quoted',
    quotedPrice: 3500,
    adminNotes: 'Quoted Rs 3500 for 5lb eggless with edible logo print',
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-22'),
  },
];

// Dashboard Stats Mock Data
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalOrders: 156,
  totalRevenue: 287500,
  pendingOrders: 12,
  completedOrders: 138,
  customOrderRequests: 8,
};
